name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - feat/add-workflow

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0.6'  # Substitua pela versão que seu projeto usa

    - name: Install Bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install --path vendor/bundle

    - name: Set up Database
      env:
        RAILS_ENV: test
      run: |
        bundle exec rails db:create
        bundle exec rails db:schema:load

    - name: Run tests
      env:
        RAILS_ENV: test
      run: bundle exec rails test
